include ../../common_config.mk

############################################################################
# Beginming of Developer Modification 
############################################################################
# for building program
application_NAME := 
# for building library
lib_NAME := liblog4z
SOVERSION := 1

program_EXT_OBJS := 
program_SUBDIRS :=
CFLAGS += -Wall -fPIC
CPPFLAGS += 
LDFLAGS += 
program_INCLUDE_DIRS := 
program_LIBRARY_DIRS := 
program_LIBRARIES := pthread dl
############################################################################
# End of Developer Modification 
############################################################################

include ../../common_rule.mk

